site_name: Haxball server documentation
repo_url: https://github.com/misProyectosPropios/haxball_server

plugins:
    - search
    - macros:
        module_name: main
    - include-markdown


use_directory_urls: false
theme: readthedocs

nav:
  - Home: index.md
  - About: about.md
  - Documentation: documentation.md
  - TestDocumentation: testDocumentation.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

extra:
    unit_price: 10